/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package yazlab1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author RECEP
 */
public class AdminPanel extends javax.swing.JFrame {

    /**
     * Creates new form AdminPanel
     */
    public AdminPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        searchtf = new javax.swing.JTextField();
        userrb = new javax.swing.JRadioButton();
        bookrb = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        searchtbl = new javax.swing.JTable();
        searchbtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        addbookbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(userrb);
        userrb.setSelected(true);
        userrb.setText("Kullanici Ara");
        userrb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userrbActionPerformed(evt);
            }
        });

        buttonGroup1.add(bookrb);
        bookrb.setText("Kitap Ara");
        bookrb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookrbActionPerformed(evt);
            }
        });

        searchtbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(searchtbl);

        searchbtn.setText("Ara");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });

        deletebtn.setText("Sil");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });

        addbookbtn.setText("Yeni Kitap Ekle");
        addbookbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbookbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(deletebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(searchtf, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bookrb)
                                    .addComponent(userrb))
                                .addGap(5, 5, 5))
                            .addComponent(addbookbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(userrb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bookrb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(searchtf, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchbtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deletebtn, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                    .addComponent(addbookbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userrbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userrbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userrbActionPerformed

    private void bookrbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookrbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookrbActionPerformed
    

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) searchtbl.getModel();
        model.setRowCount(0);
        model.setColumnCount(0);
        String search = searchtf.getText();
        YazLab1 yazlab;
        try {
            yazlab = new YazLab1();
            Connection conn = DriverManager.getConnection(yazlab.getHost(), yazlab.getUName(), yazlab.getUPass());
            Statement stmt = conn.createStatement();
            if (bookrb.isSelected()) {
                model.addColumn("isbn");
                model.addColumn("book_title");
                model.addColumn("book_author");
                model.addColumn("year_of_publication");
                model.addColumn("publisher");
                String searchQuery = "SELECT isbn,book_title,book_author,year_of_publication,publisher"
                        + " FROM bx_books WHERE book_title LIKE '%"
                        + searchtf.getText() + "%' OR isbn LIKE '%" + searchtf.getText() + "%'";
                ResultSet rs = stmt.executeQuery(searchQuery);
                System.out.println(searchQuery);
                
                while (rs.next()) {
                    model.addRow(new Object[]{rs.getString("isbn"), rs.getString("book_title"),
                        rs.getString("book_author"), rs.getString("year_of_publication"),
                        rs.getString("publisher")});
                }
                
                rs.close();
                conn.close();
            } else if (userrb.isSelected()) {
                model.addColumn("user_id");
                model.addColumn("username");
                model.addColumn("location");
                model.addColumn("age");
                String searchQuery = "SELECT user_id,username,location,age"
                        + " FROM bx_users WHERE username LIKE '%"
                        + searchtf.getText() + "%'";
                ResultSet rs = stmt.executeQuery(searchQuery);
                System.out.println(searchQuery);
                
                while (rs.next()) {
                    model.addRow(new Object[]{rs.getString("user_id"), rs.getString("username"),
                        rs.getString("location"), rs.getString("age")});
                    
                }
                
                rs.close();
                conn.close();
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        

    }//GEN-LAST:event_searchbtnActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        // TODO add your handling code here:
        YazLab1 yazlab;
        if (bookrb.isSelected()) {
            System.out.println(searchtbl.getSelectedRow());
            if (searchtbl.getSelectedRow() != -1) {
                Connection conn;
                try {
                    yazlab = new YazLab1();
                    conn = DriverManager.getConnection(yazlab.getHost(), yazlab.getUName(), yazlab.getUPass());
                    Statement stmt = conn.createStatement();
                    int selectedRow = searchtbl.getSelectedRow();
                    String deleteIsbn = (String) searchtbl.getValueAt(selectedRow, 0);
                    String deleteQuery = "DELETE FROM bx_books WHERE isbn = '" + deleteIsbn + "'";
                    stmt.executeUpdate(deleteQuery);
                    searchbtnActionPerformed(evt);
                } catch (SQLException ex) {
                    Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else if (userrb.isSelected()) {
            System.out.println(searchtbl.getSelectedRow());
            if (searchtbl.getSelectedRow() != -1) {
                Connection conn;
                try {
                    yazlab = new YazLab1();
                    conn = DriverManager.getConnection(yazlab.getHost(), yazlab.getUName(), yazlab.getUPass());
                    Statement stmt = conn.createStatement();
                    int selectedRow = searchtbl.getSelectedRow();
                    String deleteUserId = (String) searchtbl.getValueAt(selectedRow, 0);
                    String deleteQuery = "DELETE FROM bx_users WHERE user_id = '" + deleteUserId + "'";
                    stmt.executeUpdate(deleteQuery);
                    searchbtnActionPerformed(evt);
                } catch (SQLException ex) {
                    Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_deletebtnActionPerformed

    private void addbookbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbookbtnActionPerformed
        // TODO add your handling code here:
        dispose();
        new AddBook().setVisible(true);
    }//GEN-LAST:event_addbookbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPanel().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbookbtn;
    private javax.swing.JRadioButton bookrb;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton deletebtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton searchbtn;
    private javax.swing.JTable searchtbl;
    private javax.swing.JTextField searchtf;
    private javax.swing.JRadioButton userrb;
    // End of variables declaration//GEN-END:variables
}
